### ISSUE TITLE
database url

### ISSUE THREAD

**Issue by ysnghr** [Allahverdiyev-Rashad/ToDoAppWithFlask#1]
Baxdım proyektə. Ümumi proyektlə bağlı bir sıxıntı görmədim.

Lakin app run etmək istəyəndə bir problemlər qarşılaşdım.

Proyektin içərisində databasein URL səhv yerləşdirilib.

Direk öz rootundakı URL yerləşdirmək düzgün deyil.

Düzəliş edib belə bir kod yazdım.

Əvvəl:
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////Users/MSI GAMING/Desktop/ToDo/todo.db'

Sonra:
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///todo.db"

**Comment by Allahverdiyev-Rashad** [comment]
Salam çoxsağol)
